### ISSUE TITLE
detrendHeight is not exported properly

### ISSUE THREAD

**Issue by jebyrnes** [millerlp/oceanwaves#1]
When I run the demo from `?waveStatsSP` I get the following error:

`Error: 'detrendHeight' is not an exported object from 'namespace:oceanwaves'`

**Comment by jebyrnes** [comment]
`> detrendHeight`
`Error: object 'detrendHeight' not found`

**Comment by millerlp** [comment]
Updated the detrendHeight file so it exports, as well as the plotWaveSpectrum function. Also changed the waveStatsSP output from a data frame to a list, to mimic the output of waveStatsZC function.
